@extends('layouts.panel')
@section('titulo', 'Cuenta corriente')
@section('contenido')
<div class="encabezado"><div><p class="sobrelinea">Estado financiero</p><h1>Cuenta de {{ $cliente->nombre_razon_social }}</h1><p>Consultá cuotas, vencimientos y pagos registrados.</p></div><a class="boton secundario" href="{{ route('clientes.show',$cliente) }}">Volver a la ficha</a></div>
<section class="metricas"><article class="metrica"><div class="metrica-cabecera"><span>Total pendiente</span><span class="metrica-icono">$</span></div><strong>${{ number_format((float)$resumen['total_pendiente'],2,',','.') }}</strong><small>saldo sin cancelar</small></article><article class="metrica"><div class="metrica-cabecera"><span>Total vencido</span><span class="metrica-icono">!</span></div><strong>${{ number_format((float)$resumen['total_vencido'],2,',','.') }}</strong><small>requiere seguimiento</small></article><article class="metrica"><div class="metrica-cabecera"><span>Cuotas vencidas</span><span class="metrica-icono">CT</span></div><strong>{{ $resumen['cantidad_vencidas'] }}</strong><small>comprobantes pendientes</small></article><article class="metrica"><div class="metrica-cabecera"><span>Próximo vencimiento</span><span class="metrica-icono">→</span></div><strong>{{ $resumen['proximo_vencimiento'] ?? '—' }}</strong><small>siguiente fecha registrada</small></article></section>
@if ($navegacionPermitida['gestionar_cobranza'])<section class="tarjeta"><div class="tarjeta-cabecera"><div><h2>Generar cuotas mensuales</h2><p>Creá las cuotas del período para los servicios activos.</p></div></div><form class="formulario fila" method="POST" action="{{ route('cuotas.store') }}">@csrf<label>Período<input type="month" name="periodo" value="{{ now()->format('Y-m') }}" required></label><button>Generar cuotas</button></form></section>@endif
<form class="tarjeta" method="POST" action="{{ route('pagos.store') }}">@csrf<div class="tarjeta-cabecera"><div><h2>Cuotas e historial</h2><p>Seleccioná cuotas pendientes para registrar un pago.</p></div></div><div class="tabla-contenedor"><table><thead><tr><th></th><th>Período</th><th>Servicio</th><th>Vencimiento</th><th>Monto</th><th>Estado</th></tr></thead><tbody>@forelse($cuotas as $cuota)<tr><td>@if(!$cuota->id_pago && $navegacionPermitida['gestionar_pagos'])<input type="checkbox" name="cuotas[]" value="{{ $cuota->id_cuota }}" aria-label="Seleccionar cuota {{ $cuota->periodo }}">@endif</td><td>{{ $cuota->periodo }}</td><td>#{{ $cuota->id_servicio }} · {{ $cuota->servicio->plan->nombre }}</td><td>{{ $cuota->fecha_vencimiento->format('d/m/Y') }}</td><td><strong>${{ number_format((float)$cuota->monto,2,',','.') }}</strong></td><td><span class="estado {{ $cuota->estado->value }}">{{ ucfirst($cuota->estado->value) }}</span></td></tr>@empty<tr><td class="vacio" colspan="6">Todavía no hay cuotas.</td></tr>@endforelse</tbody></table></div>
@if ($navegacionPermitida['gestionar_pagos'])<div class="formulario fila"><label>Cuenta receptora<select name="id_cuenta">@foreach($cuentasReceptoras as $cuenta)<option value="{{ $cuenta->id_cuenta }}">{{ $cuenta->nombre }} · {{ $cuenta->identificador }}</option>@endforeach</select></label><label>Medio<select name="medio_pago">@foreach(['transferencia'=>'Transferencia','efectivo'=>'Efectivo','mercado_pago'=>'Mercado Pago','uala'=>'Ualá','otro'=>'Otro'] as $valor=>$etiqueta)<option value="{{ $valor }}">{{ $etiqueta }}</option>@endforeach</select></label><label>Fecha<input type="date" name="fecha" value="{{ now()->toDateString() }}"></label><button>Registrar pago</button></div>@endif</form>
@endsection
