@extends('layouts.panel')
@php($edicion = isset($servicio))
@section('titulo', $edicion ? 'Editar servicio' : 'Nuevo servicio')
@section('contenido')
<div class="encabezado"><div><p class="sobrelinea">Conexión contratada</p><h1>{{ $edicion ? 'Editar servicio' : 'Registrar servicio' }}</h1></div></div>
<form class="tarjeta formulario grilla" method="POST" action="{{ $edicion ? route('servicios.update',$servicio) : route('servicios.store') }}">@csrf @if($edicion) @method('PUT') @endif
<label>Cliente<select name="id_cliente" @disabled($edicion)>@foreach($clientes as $cliente)<option value="{{ $cliente->id_cliente }}" @selected(old('id_cliente',$servicio->id_cliente ?? '')==$cliente->id_cliente)>{{ $cliente->nombre_razon_social }}</option>@endforeach</select></label>@if($edicion)<input type="hidden" name="id_cliente" value="{{ $servicio->id_cliente }}">@endif
<label>Plan<select name="id_plan">@foreach($planes as $plan)<option value="{{ $plan->id_plan }}" @selected(old('id_plan',$servicio->id_plan ?? '')==$plan->id_plan)>{{ $plan->nombre }} · {{ $plan->velocidad }}</option>@endforeach</select></label>
<label>Calle de instalación<input name="calle_instalacion" value="{{ old('calle_instalacion',$servicio->calle_instalacion ?? '') }}" required></label><label>Número<input name="numero_instalacion" value="{{ old('numero_instalacion',$servicio->numero_instalacion ?? '') }}"></label><label>Localidad<input name="localidad_instalacion" value="{{ old('localidad_instalacion',$servicio->localidad_instalacion ?? '') }}" required></label><label>Día de vencimiento<input type="number" min="1" max="28" name="dia_vencimiento" value="{{ old('dia_vencimiento',$servicio->dia_vencimiento ?? 10) }}" required></label><label>Fecha de alta<input type="date" name="fecha_alta" value="{{ old('fecha_alta',isset($servicio)?$servicio->fecha_alta->toDateString():now()->toDateString()) }}" required></label><label>IPv4<input name="ipv4" value="{{ old('ipv4',$servicio->ipv4 ?? '') }}"></label><label>MAC<input name="mac" value="{{ old('mac',$servicio->mac ?? '') }}" placeholder="AA:BB:CC:DD:EE:FF"></label>@if($edicion)<label>Estado<select name="estado">@foreach(['activo','suspendido','baja'] as $estado)<option @selected(old('estado',$servicio->estado->value)===$estado)>{{ $estado }}</option>@endforeach</select></label>@endif
<div class="acciones ancho"><a class="boton secundario" href="{{ route('servicios.index') }}">Cancelar</a><button>Guardar</button></div></form>
@endsection
