# Generated by Django 5.2.17 on 2026-09-02 02:38

import decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaReceptora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('BANCO', 'Cuenta bancaria'), ('BILLETERA', 'Billetera virtual'), ('CAJA', 'Caja / efectivo'), ('OTRA', 'Otra')], max_length=30, verbose_name='tipo')),
                ('identificador', models.CharField(help_text='Alias, CBU/CVU, nombre de caja u otro dato identificatorio.', max_length=100, verbose_name='identificador')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'cuenta receptora',
                'verbose_name_plural': 'cuentas receptoras',
                'db_table': 'cuenta_receptora',
                'ordering': ('nombre', 'id'),
                'constraints': [models.UniqueConstraint(fields=('tipo', 'identificador'), name='uq_cuenta_identificador')],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))], verbose_name='monto total')),
                ('medio_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('MERCADO_PAGO', 'Mercado Pago'), ('OTRO', 'Otro')], max_length=30, verbose_name='medio de pago')),
                ('cuenta', models.ForeignKey(db_column='id_cuenta', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='facturacion.cuentareceptora')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'pago',
                'ordering': ('-fecha', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='El período debe utilizar el formato AAAA-MM.', regex='^\\d{4}-(0[1-9]|1[0-2])$')], verbose_name='período')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))], verbose_name='monto')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='servicios.servicio')),
                ('pago', models.ForeignKey(blank=True, db_column='id_pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='facturacion.pago')),
            ],
            options={
                'verbose_name': 'cuota',
                'verbose_name_plural': 'cuotas',
                'db_table': 'cuota',
                'ordering': ('-periodo', 'servicio_id'),
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cuenta', 'fecha'], name='ix_pago_cuenta_fecha'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto_total__gt', 0)), name='ck_pago_monto_positivo'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['pago'], name='ix_cuota_pago'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['fecha_vencimiento'], name='ix_cuota_vencimiento'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('servicio', 'periodo'), name='uq_cuota_servicio_periodo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_cuota_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vencimiento__gte', models.F('fecha_emision'))), name='ck_cuota_fechas'),
        ),
    ]
